version: "3"
services:
  kafka1:
    image: 'bitnami/kafka:latest'
    container_name: "kafka-node-1"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=BROKER
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=BROKER://:9092,CONTROLLER://:9093,CONNECTIONS_FROM_HOST://:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://kafka1:9092,CONNECTIONS_FROM_HOST://localhost:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
    ports:
      - 19092:19092
  kafka2:
    image: 'bitnami/kafka:latest'
    container_name: "kafka-node-2"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=BROKER
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=BROKER://:9092,CONTROLLER://:9093,CONNECTIONS_FROM_HOST://:19093
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://kafka2:9092,CONNECTIONS_FROM_HOST://localhost:19093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
    ports:
      - 19093:19093
  kafka3:
    image: 'bitnami/kafka:latest'
    container_name: "kafka-node-3"
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=BROKER
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=BROKER://:9092,CONTROLLER://:9093,CONNECTIONS_FROM_HOST://:19094
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://kafka3:9092,CONNECTIONS_FROM_HOST://localhost:19094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
    ports:
      - 19094:19094
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092



# KAFKA_CFG_ADVERTISED_LISTENERS this property is only for the client how they can connect to broker for producing and consuming messages.
# Behaviour:
# if KAFKA_CFG_ADVERTISED_LISTENERS is not set => it will return container_id: port on all ports that are exposed
# if it is set it checks do we have any listener advertised for this port if yes return that otherwise don't return
# eg => initialConn => brokers: [localhost:19092]  if KAFKA_CFG_ADVERTISED_LISTENERS is present and there is no
#  advertised listener for 19092 port it will not send this broker info in the metadata
# otherwise it sends the host that we have configured in advertised listener=> localhost:19092.